baseURL = "https://eugenechen0514.github.io/blog"
title = "EugeneChen"
theme = "hugo-theme-bootstrap" # install via git submodule
# theme = "github.com/razonyang/hugo-theme-bootstrap" # install via hugo module
copyright = "Copyright © 2016-{year} EugeneChen. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "zh-tw"
defaultContentLanguageInSubdir = false # If you use only one language comment this option
# disableLanguages = ["fr", "zh-cn" ,"zh-tw", "ar"] # Uncomment in order to disable one or more language
disableLanguages = ["fr", "zh-cn", "ar"] # Uncomment in order to disable one or more language

# Pagination
paginate = 10
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

enableEmoji = true

# hasCJKLanguage = true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

[blackfriday]
  hrefTargetBlank = true

[mediaTypes]
  [mediaTypes."application/manifest+json"]
    suffixes = ["json"]

[outputFormats]
  [outputFormats.MANIFEST]
    name = "manifest"
    baseName = "manifest"
    mediaType = "application/manifest+json"

[outputs]
  home = ["HTML", "RSS", "JSON", "MANIFEST"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[build]
  writeStats = true
