email = "yujiechen0514@gmail.com"
#facebook = "yourfacebookusername"
github = "eugenechen0514"
#gitlab = "yourgitlabusername"
linkedin = "in/yuchieh-chen-37a48989"

#xing = "yourxingusername"
#stackoverflow = "yourstackoverflowuserid"
#twitter = "yourtwitterusername"
#weibo = "yourweibousername"
#zhihu = "yourzhihuusername"
#instagram = "yourinstagramusername"
#quora = "yourquorausername"
#tumblr = "yourtumblrusername"
#reddit = "yourredditusername"
#telegram = "yourtelegramusername"
#qq = "yourqqnumber"
#dockerhub = "yourdockerhubusername"
#bitbucket = "yourbitbucketworkspaceid"

#kaggle = "yourkaggleusername"
medium = "yujiechen0514" # Medium username or custom domain(e.g. https://custom.domain.tld).
#lastfm = "yourlastfmusername"
bilibili = "yourbilibiliuserid"
#youtube = "youryoutubechannelid"
#discord = "yourdiscordinvitecode"
#discourse = "https://yourforum.tld"
#facebookgroup = "yourfacebookgroupname"
#tiktok = "yourtiktokusername"
#pinterest = "yourpinterestusername"
#mastodon = "yourmastodonusername"
#liberapay = "yourliberapayaccount"
#paypal="yourpaypalaccount"
#patreon="yourpatreonaccount"
#tipeee="yourtipeeeaccount-fr"
# rss = "" # Disable RSS link
